// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMHp4fQkmJ8rwqFwUh4HN5iYdrue-vl3c',
    appId: '1:284374677306:web:351e4edb2b4ab3c1e70203',
    messagingSenderId: '284374677306',
    projectId: 'wecare-8a447',
    authDomain: 'wecare-8a447.firebaseapp.com',
    databaseURL: 'https://wecare-8a447-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wecare-8a447.appspot.com',
    measurementId: 'G-3WFG4S5HKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7RRDbMnqIFV15F1FBN8kDCVzaLjPZMG4',
    appId: '1:284374677306:android:81d84003a707c3f8e70203',
    messagingSenderId: '284374677306',
    projectId: 'wecare-8a447',
    databaseURL: 'https://wecare-8a447-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wecare-8a447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp23iqHW3Xyn8GcIHS_l8CeOmf7NZMGck',
    appId: '1:284374677306:ios:14665db11a04ef1ae70203',
    messagingSenderId: '284374677306',
    projectId: 'wecare-8a447',
    databaseURL: 'https://wecare-8a447-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wecare-8a447.appspot.com',
    iosClientId: '284374677306-5gqjo6ebgrh1gujm4t968v5ouchnrpjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp23iqHW3Xyn8GcIHS_l8CeOmf7NZMGck',
    appId: '1:284374677306:ios:327f76ffe91b3756e70203',
    messagingSenderId: '284374677306',
    projectId: 'wecare-8a447',
    databaseURL: 'https://wecare-8a447-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wecare-8a447.appspot.com',
    iosClientId: '284374677306-9bcgga5gtiqn0jj4reinu3mm6rh8pb5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecare.RunnerTests',
  );
}
